name: run phpipam-action
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run phpipam-action
        uses: ./ # use action in the root directory
